export enum REDUX_ACTION {
  SET_TOKEN = "SET_TOKEN",
  EMPTY_TOKEN = "EMPTY_TOKEN",
  SET_USER = "SET_USER",
  EMPTY_USER = "EMPTY_USER",
  SET_NOTIFICATION = "SET_NOTIFICATION",
  EMPTY_NOTIFICATION = "EMPTY_NOTIFICATION",
}
